#!/bin/bash
if [ "$LIBRARIES" == "" ];
then
    exit 1
fi

OLD_IFS="$IFS"
IFS=":"
LIBRARIES_ARRAY=($LIBRARIES)
IFS="$OLD_IFS"

startServerCmd=(calibre-server)
startServerCmd+=("--port")
startServerCmd+=($RUN_PORT)
startServerCmd+=("--disable-local-write")
startServerCmd+=("--disable-use-sendfile")

for LIBRARY in "${LIBRARIES_ARRAY[@]}"
do
    LIBRARY_PATH="/calibre/data/$LIBRARY"
    if [ ! -d "$LIBRARY_PATH" ]; then
        mkdir "$LIBRARY_PATH"
        chown -R $RUN_USER:$RUN_GROUP "$LIBRARY_PATH"
    fi
    if [ ! -f "$LIBRARY_PATH/metadata.db" ]; then
        cp /calibre/metadata.db "$LIBRARY_PATH"
    fi
    startServerCmd+=("$LIBRARY_PATH")
done

trap /calibre/scripts/shutdown SIGHUP SIGINT SIGTERM TERM

"${startServerCmd[@]}"
