#!/bin/bash
if [ "$1" == "" ];
then
    echo "Usage: $0 library (identifiers | languages | pubdate | publisher | timestamp | rating)"
    exit 1
fi
LIBRARY_PATH="/calibre/data/$1"
if [ ! -d "$LIBRARY_PATH" ];
then
    echo "Usage: $0 library (identifiers | languages | pubdate | publisher | timestamp | rating)"
    exit 1
fi
if [ ! -f "$LIBRARY_PATH/metadata.db" ];
then
    echo "Usage: $0 library (identifiers | languages | pubdate | publisher | timestamp | rating)"
    exit 1
fi
if [ "$2" != "identifiers" ] && [ "$2" != "languages" ] && [ "$2" != "pubdate" ] && [ "$2" != "publisher" ] && [ "$2" != "timestamp" ] && [ "$2" != "rating" ];
then
    echo "Usage: $0 library (identifiers | languages | pubdate | publisher | timestamp | rating)"
    exit 1
fi

source /calibre/scripts/containerConfig

$stopWebCmd

if [ "$2" == "identifiers" ] || [ "$2" == "languages" ] || [ "$2" == "pubdate" ] || [ "$2" == "publisher" ] || [ "$2" == "timestamp" ];
then
    calibredb --with-library $LIBRARY_PATH list -f id | tail -n+2 | xargs -n 1 -x calibredb --with-library $LIBRARY_PATH set_metadata -f $2:
fi
if [ "$2" == "rating" ];
then
    calibredb --with-library $LIBRARY_PATH list -f id | tail -n+2 | xargs -n 1 -x calibredb --with-library $LIBRARY_PATH set_metadata -f $2:0
fi

$startWebCmd
