#!/bin/bash
if [ "$1" != "" ];
then
    TEMPFILE="/calibre/backups/tmp_$1.tar.gz"
    FILE="/calibre/backups/$1.tar.gz"
    source /calibre/scripts/containerConfig

    $stopWebCmd

    cd /calibre
    tar -czf $TEMPFILE data
    rm -rf $FILE
    mv $TEMPFILE $FILE

    $startWebCmd
fi
